const qs=(s,c=document)=>c.querySelector(s),qsa=(s,c=document)=>[...c.querySelectorAll(s)];
const nav=qs('[data-nav]'),menu=qs('.menu'),panel=qs('.mobile-panel'),progress=qs('.scroll-progress span'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
requestAnimationFrame(()=>document.body.classList.add('ready'));
const closeMenu=()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');panel?.setAttribute('aria-hidden','true')};
menu?.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');panel?.setAttribute('aria-hidden',String(!open))});
qsa('.mobile-panel a,.nav-links a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
let scrollTick=false;const updateScroll=()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;nav.classList.toggle('scrolled',y>18);if(progress)progress.style.transform=`scaleX(${max>0?Math.min(1,y/max):0})`;scrollTick=false};addEventListener('scroll',()=>{if(!scrollTick){scrollTick=true;requestAnimationFrame(updateScroll)}},{passive:true});updateScroll();
const revealEls=qsa('[data-reveal]');if(reduce){revealEls.forEach(el=>el.classList.add('visible'))}else{const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -5%'});revealEls.forEach((el,i)=>{el.style.transitionDelay=`${Math.min((i%4)*55,165)}ms`;revealObserver.observe(el)})}
const sectionLinks=new Map(qsa('.nav-links a').map(a=>[a.getAttribute('href')?.slice(1),a]));const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){qsa('.nav-links a').forEach(a=>a.classList.remove('active'));sectionLinks.get(entry.target.id)?.classList.add('active')}}),{rootMargin:'-35% 0px -55%',threshold:0});qsa('[data-section][id]').forEach(s=>sectionObserver.observe(s));
const process=qs('.process');if(process){const po=new IntersectionObserver(([e])=>{if(e.isIntersecting){process.classList.add('in-view');po.disconnect()}},{threshold:.25});po.observe(process)}
if(fine&&!reduce){qsa('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform=`translate3d(${x*.08}px,${y*.12}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
if(fine&&!reduce){const stage=qs('.hero-stage');if(stage){const depthEls=qsa('[data-depth]',stage);stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect(),nx=(e.clientX-r.left)/r.width-.5,ny=(e.clientY-r.top)/r.height-.5;depthEls.forEach(el=>{const d=Number(el.dataset.depth||.3);el.style.translate=`${nx*18*d}px ${ny*14*d}px`})});stage.addEventListener('pointerleave',()=>depthEls.forEach(el=>el.style.translate='0 0'))}}
if(fine&&!reduce){qsa('[data-case] .case-media').forEach(media=>{const img=qs('img',media);media.addEventListener('pointermove',e=>{const r=media.getBoundingClientRect(),nx=(e.clientX-r.left)/r.width-.5,ny=(e.clientY-r.top)/r.height-.5;img.style.translate=`${nx*-8}px ${ny*-5}px`});media.addEventListener('pointerleave',()=>img.style.translate='0 0')})}
if(!reduce&&matchMedia('(max-width:720px)').matches){let mobileMarquees=[];const startMarquees=()=>{mobileMarquees.forEach(a=>a.cancel());mobileMarquees=[];[['.ticker-track',30000],['.contact-marquee>div',15000]].forEach(([sel,duration])=>{const el=qs(sel);if(!el||!el.animate)return;el.style.animation='none';const distance=el.scrollWidth/2;if(distance>0)mobileMarquees.push(el.animate([{transform:'translate3d(0,0,0)'},{transform:`translate3d(-${distance}px,0,0)`}],{duration,iterations:Infinity,easing:'linear'}))})};(document.fonts?.ready||Promise.resolve()).then(startMarquees);let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(startMarquees,180)},{passive:true})}
qsa('.faq-list details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)qsa('.faq-list details').forEach(other=>{if(other!==d)other.open=false})}));
qs('#year').textContent=new Date().getFullYear();qs('#leadForm')?.addEventListener('submit',e=>{e.preventDefault();const name=qs('#name').value.trim(),type=qs('#type').value,msg=qs('#message').value.trim();const text=`Olá Yagho, vim pelo seu site.\n\nMeu nome: ${name}\nTipo de negócio: ${type}\n\nProjeto: ${msg}`;window.open(`https://wa.me/5553999563554?text=${encodeURIComponent(text)}`,'_blank','noopener')});
